# spring.application.name=backend
# # TEMP DB (H2)
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=none

spring.application.name=backend

spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.lsvnudvaqimlzhulrtbo
spring.datasource.password=SakshamFSD123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# spring.datasource.url=jdbc:postgresql://db.lsvnudvaqimlzhulrtbo.supabase.co:5432/postgres?sslmode=require
# spring.datasource.username=postgres
# spring.datasource.password=SakshamFSD123

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2



supabase.url=https://lsvnudvaqimlzhulrtbo.supabase.co
supabase.service-role-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxzdm51ZHZhcWltbHpodWxydGJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE2OTIxMjYsImV4cCI6MjA4NzI2ODEyNn0.u9Avbx-h5g7OR68FgHqP8QzOz_XHzxClxnFwlUHM0ug