# spring.application.name=backend
# # TEMP DB (H2)
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=none
spring.application.name=backend

spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.lsvnudvaqimlzhulrtbo
spring.datasource.password=SakshamFSD123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# OpenRouter API Configuration
openrouter.api.key=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
openrouter.api.url=https://openrouter.ai/api/v1/chat/completions
openrouter.api.model=openai/gpt-oss-20b:free