spring.application.name=backend

server.port=${PORT:8080}

# ================= DATABASE =================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ================= OPENROUTER =================
openrouter.api.key=${OPENROUTER_KEY}
openrouter.api.url=https://openrouter.ai/api/v1/chat/completions
openrouter.api.model=openai/gpt-oss-20b:free
gemini.api.key=${GOOGLE_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1/models/gemini-1.5-flash:generateContent
# gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent

# ================= HIKARI CONNECTION POOL =================
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2

# ================= SUPABASE =================
supabase.url=https://lsvnudvaqimlzhulrtbo.supabase.co
supabase.service-role-key=${SUPABASE_KEY}

# ================= MAIL =================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ================= FRONTEND =================
app.frontend.reset-password-url=${FRONTEND_RESET_URL}

calendly.token=eyJraWQiOiIxY2UxZTEzNjE3ZGNmNzY2YjNjZWJjY2Y4ZGM1YmFmYThhNjVlNjg0MDIzZjdjMzJiZTgzNDliMjM4MDEzNWI0IiwidHlwIjoiUEFUIiwiYWxnIjoiRVMyNTYifQ.eyJpc3MiOiJodHRwczovL2F1dGguY2FsZW5kbHkuY29tIiwiaWF0IjoxNzc0NzM0Nzc5LCJqdGkiOiI3MTM3Y2NmMS1kNTdkLTQ5MDQtYjcyZS0xNTJjZmNhN2Q1NGEiLCJ1c2VyX3V1aWQiOiIzOWYzZTIzZi1mMDAwLTQ5ZTQtOGE2MS1hYjAyNTlkMTM5MzQiLCJzY29wZSI6InNjaGVkdWxlZF9ldmVudHM6cmVhZCB1c2VyczpyZWFkIn0.HIxGr5Kh1SkpsQIMe4fNRpysiectsEbdTvANAX7g0Rf0xVjxVmkz_GJov2hWY-qXx5SInlXRMSmkmfTBoawiwg